language: php

services:
  - rabbitmq
  - redis-server
  - memcached

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo pear channel-discover pear.zero.mq
  - sudo pecl install pear.zero.mq/zmq-beta
  - sudo apt-get install libhiredis-dev
  - git clone --quiet https://github.com/nrk/phpiredis.git
  - sh -c "cd phpiredis && phpize && ./configure --enable-phpiredis --with-hiredis-dir=/usr/local && make --silent && sudo make install"
  - echo "extension=phpiredis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit --coverage-text
