<?php

namespace Gloubster\Client;

require_once dirname(__FILE__) . '/../../../../src/Gloubster/Client/RunClient.php';

/**
 * Test class for RunClient.
 * Generated by PHPUnit on 2012-07-04 at 18:11:25.
 */
class RunClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RunClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new RunClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Gloubster\Client\RunClient::__contruct
     * @todo Implement test__contruct().
     */
    public function test__contruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Gloubster\Client\RunClient::execute
     * @todo Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}

?>
