<?php

namespace DoctrineMongoDBHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class GloubsterDocumentsJobHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['error'])) {
            $value = $data['error'];
            $return = (bool) $value;
            $this->class->reflFields['error']->setValue($document, $return);
            $hydratedData['error'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['errorMessage'])) {
            $value = $data['errorMessage'];
            $return = (string) $value;
            $this->class->reflFields['errorMessage']->setValue($document, $return);
            $hydratedData['errorMessage'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['workerId'])) {
            $value = $data['workerId'];
            $return = (string) $value;
            $this->class->reflFields['workerId']->setValue($document, $return);
            $hydratedData['workerId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['beginning'])) {
            $value = $data['beginning'];
            $return = (string) $value;
            $this->class->reflFields['beginning']->setValue($document, $return);
            $hydratedData['beginning'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['end'])) {
            $value = $data['end'];
            $return = (string) $value;
            $this->class->reflFields['end']->setValue($document, $return);
            $hydratedData['end'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['delivery'])) {
            $value = $data['delivery'];
            $return = (string) $value;
            $this->class->reflFields['delivery']->setValue($document, $return);
            $hydratedData['delivery'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['deliveryId'])) {
            $value = $data['deliveryId'];
            $return = (string) $value;
            $this->class->reflFields['deliveryId']->setValue($document, $return);
            $hydratedData['deliveryId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['processDuration'])) {
            $value = $data['processDuration'];
            $return = (string) $value;
            $this->class->reflFields['processDuration']->setValue($document, $return);
            $hydratedData['processDuration'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['deliveryDuration'])) {
            $value = $data['deliveryDuration'];
            $return = (string) $value;
            $this->class->reflFields['deliveryDuration']->setValue($document, $return);
            $hydratedData['deliveryDuration'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['routingKey'])) {
            $value = $data['routingKey'];
            $return = (string) $value;
            $this->class->reflFields['routingKey']->setValue($document, $return);
            $hydratedData['routingKey'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['exchangeName'])) {
            $value = $data['exchangeName'];
            $return = (string) $value;
            $this->class->reflFields['exchangeName']->setValue($document, $return);
            $hydratedData['exchangeName'] = $return;
        }
        return $hydratedData;
    }
}